"""Add tab_penalty_enabled to Game

Revision ID: 10ec0273c5a1
Revises: 6bcc3e6a8c04
Create Date: 2025-12-15 15:39:51.429369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ec0273c5a1'
down_revision = '6bcc3e6a8c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_penalty_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('tab_penalty_enabled')

    # ### end Alembic commands ###
