"""Add pause_mode field to Game model

Revision ID: 22052d1e371b
Revises: 4271162457ea
Create Date: 2025-12-16 19:33:14.223541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22052d1e371b'
down_revision = '4271162457ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('pause_mode')

    # ### end Alembic commands ###
