"""Add timer_end_time to Round

Revision ID: 2fc313a945ba
Revises: 10ec0273c5a1
Create Date: 2025-12-15 19:15:03.354179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc313a945ba'
down_revision = '10ec0273c5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_end_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_column('timer_end_time')

    # ### end Alembic commands ###
