"""Add tab_switch_count to Team model

Revision ID: 9b1feac8bd29
Revises: 22052d1e371b
Create Date: 2025-12-17 04:20:48.524836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1feac8bd29'
down_revision = '22052d1e371b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_switch_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('tab_switch_count')

    # ### end Alembic commands ###
