"""Add tab_away_seconds to Team

Revision ID: be7b8d9f90fb
Revises: 114e65e44ff4
Create Date: 2025-12-14 00:51:03.888899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7b8d9f90fb'
down_revision = '114e65e44ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_away_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('tab_away_seconds')

    # ### end Alembic commands ###
