"""Add logout_count to Team model

Revision ID: f76c892c2474
Revises: f9f1419a1671
Create Date: 2025-12-17 05:04:17.201611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76c892c2474'
down_revision = 'f9f1419a1671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logout_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('logout_count')

    # ### end Alembic commands ###
